name: Publish
on:
  push:
    tags: ['v[0-9]*.[0-9]*.[0-9]*']
jobs:
  publish:
    permissions:
      id-token: write
      contents: write
    uses: refilelabs/.github/.github/workflows/wasm-publish.yml@main
